title: Anjan Kumar Regulavalasa # your name (or website title) here
logo: "/images/my photo.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Summary
  <br>Anjan is a data-driven professional with a Master's in Business Analytics and a background in Civil Engineering. 
  He is proficient in R, Python, and SQL programming, and skilled in using Microsoft PowerBI and Tableau for analytics 
  and visualization. With over 4 years of project management and data analysis experience, he excels at informed decision-making,
  risk identification, and resource management.<br>
  
  <a href="https://www.linkedin.com/in/anjani-kumar-rvr/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
